[training]
nr_of_epochs = 1_000
save_dir = "training"
experiment_name = "train_on_energies"
accelerator = "gpu"
num_nodes = 1
devices = 1                           #[0,1,2,3]
batch_size = 512
remove_self_energies = true
pin_memory = true

training_parameter.lr = 1e-3
training_parameter.lr_scheduler_config.frequency = 1
training_parameter.lr_scheduler_config.mode = "min"
training_parameter.lr_scheduler_config.factor = 0.1
training_parameter.lr_scheduler_config.patience = 10
training_parameter.lr_scheduler_config.cooldown = 5
training_parameter.lr_scheduler_config.min_lr = 1e-8
training_parameter.lr_scheduler_config.threshold = 0.1
training_parameter.lr_scheduler_config.threshold_mode = "abs"
training_parameter.lr_scheduler_config.monitor = "val/energy/rmse"
training_parameter.lr_scheduler_config.interval = "epoch"

early_stopping.verbose = true
early_stopping.monitor = "val/energy/rmse"
early_stopping.min_delta = 0.001
early_stopping.patience = 50

loss_parameter.loss_type = "EnergyLoss"
