[potential]
potential_parameter.angle_sections = 4
potential_parameter.radial_max_distance = "5.1 angstrom"
potential_parameter.radial_min_distance = "0.8 angstrom"
potential_parameter.number_of_radial_basis_functions = 16
potential_parameter.angular_max_distance = "3.5 angstrom"
potential_parameter.angular_min_distance = "0.8 angstrom"
potential_parameter.angular_dist_divisions = 8
model_name = "ANI2x"

[training]
nr_of_epochs = 50
save_dir = "test"
experiment_name = "your_experiment_name"
accelerator = "gpu"
num_nodes = 1
devices = [2]                            #[0,1,2,3]
include_force = true

training_parameter.lr = 1e-3
training_parameter.lr_scheduler_config.frequency = 1
training_parameter.lr_scheduler_config.mode = "min"
training_parameter.lr_scheduler_config.factor = 0.1
training_parameter.lr_scheduler_config.patience = 10
training_parameter.lr_scheduler_config.cooldown = 5
training_parameter.lr_scheduler_config.min_lr = 1e-8
training_parameter.lr_scheduler_config.threshold = 0.1
training_parameter.lr_scheduler_config.threshold_mode = "abs"
training_parameter.lr_scheduler_config.monitor = "rmse_val_loss"
training_parameter.lr_scheduler_config.interval = "epoch"

early_stopping.verbose = true
early_stopping.monitor = "rmse_val_loss"
early_stopping.min_delta = 0.001
early_stopping.patience = 50

stochastic_weight_averaging_config.swa_epoch_start = 50
stochastic_weight_averaging_config.swa_lrs = 1e-2

[dataset]
dataset_name = "phalkethoh"
batch_size = 512
remove_self_energies = true
