[potential]
potential_parameters.max_Z = 101
potential_parameters.number_of_atom_features = 32
potential_parameters.number_of_radial_basis_functions = 20
potential_parameters.cutoff = "5.0 angstrom"
potential_parameters.number_of_interaction_modules = 3
potential_parameters.number_of_filters = 32
potential_parameters.shared_interactions = false
model_name = "SchNet"

[training]
nr_of_epochs = 50
save_dir = "test"
experiment_name = "your_experiment_name"
accelerator = "cpu"
training_parameters = {}
num_nodes = 1
devices = 1                              #[0,1,2,3]
early_stopping.monitor = "rmse_val_loss"
early_stopping.min_delta = 0.001
early_stopping.patience = 50
early_stopping.verbose = true

[dataset]
dataset_name = "QM9"
batch_size = 512
remove_self_energies = true
