[potential]
potential_name = "TensorNet"

hidden_channels = 8
number_of_interaction_layers = 2
number_of_radial_basis_functions = 16
radial_max_distance = "5.1 angstrom"
radial_min_distance = "0.0 angstrom"
maximum_atomic_number = 101
equivariance_invariance_group = "O(3)"

[potential.postprocessing_parameter]
[potential.postprocessing_parameter.per_atom_energy]
normalize = true
from_atom_to_molecule_reduction = true
keep_per_atom_property = true
[potential.postprocessing_parameter.general_postprocessing_operation]
calculate_molecular_self_energy = true[dataset]
dataset_name = "QM9"

[training]
save_dir = "test"
experiment_name = "your_experiment_name"
accelerator = "cpu"
num_nodes = 1
devices = 1                              # [0,1,2,3]
remove_self_energies = true
batch_size = 128

[training.training_parameter]
lr = 1e-3

[training.training_parameter.lr_scheduler_config]
frequency = 1
mode = "min"
factor = 0.1
patience = 10
cooldown = 5
min_lr = 1e-8
threshold = 0.1
threshold_mode = "abs"
monitor = "val/per_molecule_energy/rmse"
interval = "epoch"

[training.training_parameter.loss_parameter]
loss_property = ['per_molecule_energy'] # use .
[training.training_parameter.loss_parameter.weight]
per_molecule_energy = 0.999 #NOTE: reciproce units
per_atom_force = 0.001

[training.early_stopping]
verbose = true
monitor = "val/per_molecule_energy/rmse"
min_delta = 0.001
patience = 50

[training.experiment_logger]
logger_name = "wandb"
save_dir = "test"
experiment_name = "{potential_name}_{dataset_name}"


[training.splitting_strategy]
name = "random_record_splitting_strategy"
data_split = [0.8, 0.1, 0.1]

[runtime]
accelerator = "cpu"
num_nodes = 1
devices = 1                 #[0,1,2,3]
local_cache_dir = "./cache"
nr_of_epochs = 10